# GitHub Repository Settings Configuration
# This file can be used with GitHub CLI to configure repository settings
# Run: gh repo edit --add-topic smart-locker,iot,flask,react --description "Smart Locker Management System"

# Repository Settings
repository:
  name: smart_locker_project
  description: "Smart Locker Management System with Flask backend and React frontend"
  homepage: "https://github.com/ezores/smart_locker_project"
  topics:
    ["smart-locker", "iot", "flask", "react", "postgresql", "management-system"]
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: "main"
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  allow_auto_merge: false
  allow_update_branch: true

# Branch Protection Rules
branches:
  - name: "main"
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "backend-tests"
          - "frontend-tests"
          - "integration-tests"
          - "security-scan"
          - "code-quality"
          - "build-and-test"
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        require_last_push_approval: false
      restrictions:
        users: []
        teams: []
        apps: []
      required_linear_history: false
      allow_force_pushes: false
      allow_deletions: false
      block_creations: false
      required_conversation_resolution: true

  - name: "develop"
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "backend-tests"
          - "frontend-tests"
          - "integration-tests"
          - "security-scan"
          - "code-quality"
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        require_last_push_approval: false
      restrictions:
        users: []
        teams: []
        apps: []
      required_linear_history: false
      allow_force_pushes: false
      allow_deletions: false
      block_creations: false
      required_conversation_resolution: true

# Issue Templates
issue_templates:
  - name: "Bug Report"
    about: "Create a report to help us improve"
    title: "[BUG] "
    labels: ["bug"]
    body: |
      **Describe the bug**
      A clear and concise description of what the bug is.

      **To Reproduce**
      Steps to reproduce the behavior:
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error

      **Expected behavior**
      A clear and concise description of what you expected to happen.

      **Screenshots**
      If applicable, add screenshots to help explain your problem.

      **Environment:**
      - OS: [e.g. macOS, Windows, Linux]
      - Browser: [e.g. Chrome, Safari, Firefox]
      - Version: [e.g. 22]

      **Additional context**
      Add any other context about the problem here.

  - name: "Feature Request"
    about: "Suggest an idea for this project"
    title: "[FEATURE] "
    labels: ["enhancement"]
    body: |
      **Is your feature request related to a problem? Please describe.**
      A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

      **Describe the solution you'd like**
      A clear and concise description of what you want to happen.

      **Describe alternatives you've considered**
      A clear and concise description of any alternative solutions or features you've considered.

      **Additional context**
      Add any other context or screenshots about the feature request here.

# Security Settings
security_and_analysis:
  secret_scanning:
    status: "enabled"
  secret_scanning_push_protection:
    status: "enabled"
  dependabot_security_updates:
    status: "enabled"
  dependabot_version_updates:
    status: "enabled"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"

# Actions Settings
actions:
  allowed_actions: "selected"
  github_owned_allowed: true
  verified_allowed: true
  patterns_allowed: []
