import React from "react";
import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

const translations = {
  en: {
    // Navigation
    main_menu: "Main Menu",
    borrow: "Borrow",
    return: "Return",
    admin: "Admin",
    users: "Users",
    items: "Items",
    lockers: "Lockers",
    logs: "Logs",
    logout: "Logout",

    // Login
    login: "Login",
    username: "Username",
    password: "Password",
    login_button: "Sign In",
    login_error: "Invalid username or password",
    login_description: "Sign in to access the Smart Locker System",
    enter_username: "Enter your username",
    enter_password: "Enter your password",
    fill_all_fields: "Please fill in all fields",
    demo_credentials:
      "Demo credentials: admin/admin123, student1/student123, manager/manager123, supervisor/supervisor123",
    dont_have_account: "Don't have an account?",
    sign_in: "Sign in",
    server_error: "Server error. Please try again later.",
    network_error: "Network error. Please check your connection.",
    login_failed: "Login failed. Please try again.",
    invalid_credentials: "Invalid username or password. Please try again.",
    account_locked: "Account is locked. Please contact administrator.",
    too_many_attempts: "Too many login attempts. Please try again later.",

    // Main Menu
    welcome: "Welcome",
    select_option: "Please select an option",
    borrow_item: "Borrow an Item",
    return_item: "Return an Item",
    admin_panel: "Admin Panel",
    borrow_description: "Borrow equipment or tools from available lockers",
    return_description: "Return borrowed items to their assigned lockers",
    admin_panel_description:
      "Access administrative functions and system management",
    items_description: "Manage equipment and tools inventory",
    lockers_description: "Configure and monitor locker status",
    payments_menu_description: "Manage payments and billing information",
    get_started: "Get started",
    quick_overview: "Quick Overview",

    // Borrow
    follow_steps_borrow: "Follow the steps to borrow an item",
    authentication: "Authentication",
    choose_authentication_method: "Choose your authentication method",
    rfid_card: "RFID Card",
    scan_rfid: "Scan RFID Card",
    scan_rfid_description: "Please scan your RFID card to continue",
    simulate_rfid_scan: "Simulate RFID Scan",
    user_id: "User ID",
    enter_user_id: "Enter your user ID",
    enter_user_id_description:
      "Enter your numeric user ID if you don't have your RFID card",
    continue: "Continue",
    select_item: "Select Item",
    choose_item_borrow: "Choose the item you want to borrow",
    select_locker: "Select Locker",
    select_available_locker: "Select an available locker for your item",
    confirm_borrow: "Confirm Borrow",
    confirm_borrowing_details: "Please confirm your borrowing details",
    borrow_success: "Item borrowed successfully",
    borrow_error: "Failed to borrow item",
    // Return
    follow_steps_return: "Follow the steps to return an item",
    scan_rfid_return_description:
      "Please scan your RFID card to return your item",
    enter_user_id_return_description:
      "Enter your numeric user ID to return your item",
    select_item_return: "Select Item to Return",
    choose_item_return: "Choose the item you want to return",
    confirm_return: "Confirm Return",
    confirm_return_details: "Please confirm your return details",
    return_success: "Item returned successfully",
    return_error: "Failed to return item",
    error_fetching_items: "Error fetching borrowed items",
    borrowed_on: "Borrowed on",
    back_to_main_menu: "Back to Main Menu",
    // Dashboard
    dashboard_description: "Overview of the Smart Locker System",
    // Items Management
    items_management: "Items Management",
    items_management_description:
      "Manage equipment and tools in the locker system",
    search_items: "Search items...",
    search_borrowed_items: "Search borrowed items...",
    no_items_found: "No items found",
    try_different_search: "Try a different search term",
    all_lockers: "All Lockers",
    add_item: "Add Item",
    edit_item: "Edit Item",
    delete_item: "Delete Item",
    confirm_delete_item: "Are you sure you want to delete this item?",
    failed_add_item: "Failed to add item",
    failed_update_item: "Failed to update item",
    failed_delete_item: "Failed to delete item",
    // Active Borrows (Emprunts)
    active_borrows: "Active Borrows",
    active_borrows_description: "View and manage all currently borrowed items",
    active_borrows_menu_description: "View all active borrows and their status",
    search_borrows: "Search borrows...",
    filter_by_user: "Filter by User",
    filter_by_item: "Filter by Item",
    filter_by_date: "Filter by Date",
    all_users: "All Users",
    all_items: "All Items",
    showing: "Showing",
    of: "of",
    duration: "Duration",
    days: "days",
    hours: "hours",
    less_than_hour: "Less than 1 hour",
    no_active_borrows: "No Active Borrows",
    no_active_borrows_description:
      "There are currently no active borrows in the system",
    failed_export_borrows: "Failed to export borrows",

    // Admin
    dashboard: "Dashboard",
    total_users: "Total Users",
    total_items: "Total Items",
    total_lockers: "Total Lockers",
    recent_activity: "Recent Activity",
    view_current_borrows: "View currently borrowed items",
    view_activity_logs: "View all system activity",
    add_edit_users: "Add, edit, or remove users",
    completed: "Completed",
    unknown: "Unknown",

    // Common
    loading: "Loading...",
    error: "Error",
    success: "Success",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    search: "Search",
    no_data: "No data available",

    // Registration
    create_account: "Create your account",
    register_description: "Join the Smart Locker System",
    register: "Register",
    email: "Email",
    first_name: "First Name",
    last_name: "Last Name",
    confirm_password: "Confirm Password",
    already_have_account: "Already have an account?",
    username_placeholder: "Enter username",
    email_placeholder: "Enter email address",
    first_name_placeholder: "Enter first name",
    last_name_placeholder: "Enter last name",
    password_placeholder: "Enter password",
    confirm_password_placeholder: "Confirm your password",
    password_requirements: "Password requirements:",
    min_8_characters: "At least 8 characters",
    one_uppercase: "One uppercase letter",
    one_lowercase: "One lowercase letter",
    one_number: "One number",
    one_special: "One special character",
    all_fields_required: "All fields are required",
    passwords_dont_match: "Passwords don't match",
    password_requirements_not_met: "Password requirements not met",
    invalid_email: "Invalid email address",
    registration_successful: "Registration successful! Please log in.",
    registration_failed: "Registration failed. Please try again.",
    student_id: "Student ID",
    student_id_placeholder: "Enter your student ID",
    scan_card: "Scan Card",
    scan_card_description: "Or scan your student card",
    generate_test_id: "Generate Test ID",

    // User Management
    add_user: "Add User",
    edit_user: "Edit User",
    delete_user: "Delete User",
    search_users: "Search users...",
    filter_by_role: "Filter by role",
    all_roles: "All Roles",
    new_password: "New Password",
    leave_blank: "leave blank to keep current",
    role: "Role",
    student: "Student",
    user_management: "User Management",
    manage_accounts: "Manage user accounts and permissions",
    no_users_found: "No users found",
    get_started_adding: "Get started by adding your first user",
    user: "User",
    actions: "Actions",
    confirm_delete: "Are you sure you want to delete this user?",
    failed_add_user: "Failed to add user",
    failed_update_user: "Failed to update user",
    failed_delete_user: "Failed to delete user",
    save_changes: "Save Changes",

    // Reports
    reports: "Reports",
    report_type: "Report Type",
    date_range: "Date Range",
    start_date: "Start Date",
    end_date: "End Date",
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    yearly: "Yearly",
    transactions: "Transactions",
    export_excel: "Export Excel",
    export_pdf: "Export PDF",
    generate: "Generate",
    generating: "Generating...",
    summary: "Summary",
    total_transactions: "Total Transactions",
    borrows: "Borrows",
    returns: "Returns",
    unique_users: "Unique Users",
    unique_items: "Unique Items",
    transaction_details: "Transaction Details",
    action: "Action",
    timestamp: "Timestamp",
    locker: "Locker",
    overview: "Overview",
    quick_actions: "Quick Actions",
    generate_report: "Generate Report",
    view_transactions: "View transactions and analytics",

    // Lockers
    lockers_management: "Lockers Management",
    edit_locker: "Edit Locker",
    locker_name: "Locker Name",
    location: "Location",
    status: "Status",
    available: "Available",
    occupied: "Occupied",
    maintenance: "Maintenance",
    reserved: "Reserved",
    inactive: "Inactive",
    available_lockers: "Available Lockers",
    reserved_lockers: "Reserved Lockers",
    maintenance_lockers: "Maintenance Lockers",
    inactive_lockers: "Inactive Lockers",
    no_available_lockers: "No Available Lockers",
    all_lockers_occupied:
      "All lockers are currently occupied or under maintenance.",
    locker_with_item: "Locker with Selected Item",
    empty_lockers: "Empty Lockers",
    contains_item: "Contains Item",
    no_item: "No Item",
    item_locker_unavailable: "Item's Locker Unavailable",
    item_locker_unavailable_desc:
      "The locker containing this item is currently unavailable (maintenance, reserved, or inactive).",
    no_borrowed_items: "No Borrowed Items",
    no_borrowed_items_desc:
      "You don't have any items currently borrowed. Visit the Borrow page to borrow items.",
    lockers_management_description: "Manage locker locations and status",
    search_lockers: "Search lockers...",
    all_status: "All Status",
    no_lockers_found: "No lockers found",
    get_started_adding_locker: "Get started by adding your first locker",
    rs485_configuration: "RS485 Configuration",
    rs485_address: "RS485 Address",
    rs485_address_help: "Address card (0-31 dipswitch)",
    rs485_locker_number: "Locker Number",
    rs485_locker_number_help: "Number of locker (1-24)",
    rs485_protocol_info:
      "Protocol: 5A5A 00 [ADDRESS] 00 04 00 01 [LOCKER_NUMBER] [CHECKSUM]",

    // Logs
    logs_title: "System Logs",
    logs_description: "Monitor system activity and user actions",
    search_logs: "Search logs...",
    all_actions: "All Actions",
    filters: "Filters",
    export_csv: "Export CSV",
    clear_filters: "Clear Filters",
    no_logs_found: "No logs found",
    try_adjusting_search: "Try adjusting your search or filter criteria",
    no_activity_logged: "No activity has been logged yet",
    unknown_user: "Unknown User",
    unknown_item: "Unknown Item",
    unknown_locker: "Unknown Locker",
    just_now: "Just now",
    minutes_ago: "minutes ago",
    hours_ago: "hours ago",
    failed_export_logs: "Failed to export logs",

    // Payments
    payments: "Payments",
    payments_description: "Manage payments and billing information",
    search_payments: "Search payments...",
    new_payment: "New Payment",
    download_excel: "Download Excel",
    add_money: "Add Money",
    balance: "Balance",
    amount: "Amount",
    description: "Description",
    date: "Date",
    currency: "Currency",
    payment_history: "Payment History",
    no_payments_found: "No payments found",
    no_payments_yet: "No payments have been made yet",
    failed_add_payment: "Failed to add payment",
    failed_add_money: "Failed to add money",
    all_statuses: "All Statuses",
    failed: "Failed",
    show: "Show",
    per_page: "per page",
    all: "All",
    page: "Page",
    add_locker: "Add Locker",
    item_name: "Item Name",
    description_optional: "Description (Optional)",
    system_logs: "System Logs",
    manage_users: "Manage Users",
    my_balance: "My Balance",
    balance_description: "Manage your account balance and payment history",
    current_balance: "Current Balance",

    // Reservations
    reservations: "Reservations",
    reservations_menu_description: "Manage and schedule locker reservations",
    "reservations.title": "Reservations",
    "reservations.allStatuses": "All Statuses",
    "reservations.active": "Active",
    "reservations.cancelled": "Cancelled",
    "reservations.completed": "Completed",
    "reservations.expired": "Expired",
    "reservations.createNew": "Create New Reservation",
    "reservations.calendar": "Calendar",
    "reservations.reservationsFor": "Reservations for",
    "reservations.allReservations": "All Reservations",
    "reservations.reservationCode": "Reservation Code",
    "reservations.startTime": "Start Time",
    "reservations.endTime": "End Time",
    "reservations.accessCode": "Access Code",
    "reservations.notes": "Notes",
    "reservations.edit": "Edit",
    "reservations.cancel": "Cancel",
    "reservations.noReservations": "No reservations found",
    "reservations.locker": "Locker",
    "reservations.selectLocker": "Select a locker",
    "reservations.creating": "Creating...",
    "reservations.create": "Create",
    "reservations.editReservation": "Edit Reservation",
    "reservations.updating": "Updating...",
    "reservations.update": "Update",
    "reservations.confirmCancel":
      "Are you sure you want to cancel this reservation?",
  },
  fr: {
    main_menu: "Menu Principal",
    borrow: "Emprunter",
    return: "Retourner",
    admin: "Administration",
    users: "Utilisateurs",
    items: "Articles",
    lockers: "Casiers",
    logs: "Journaux",
    logout: "Déconnexion",
    login: "Connexion",
    username: "Nom d'utilisateur",
    password: "Mot de passe",
    login_button: "Se Connecter",
    login_error: "Nom d'utilisateur ou mot de passe invalide",
    login_description:
      "Connectez-vous pour accéder au système de casiers intelligents",
    enter_username: "Entrez votre nom d'utilisateur",
    enter_password: "Entrez votre mot de passe",
    fill_all_fields: "Veuillez remplir tous les champs",
    demo_credentials:
      "Identifiants de démonstration: admin/admin123, student1/student123, manager/manager123, supervisor/supervisor123",
    dont_have_account: "Vous n'avez pas de compte ?",
    sign_in: "Se connecter",
    server_error: "Erreur du serveur. Veuillez réessayer plus tard.",
    network_error: "Erreur de réseau. Veuillez vérifier votre connexion.",
    login_failed: "Échec de la connexion. Veuillez réessayer.",
    invalid_credentials:
      "Nom d'utilisateur ou mot de passe invalide. Veuillez réessayer.",
    account_locked: "Compte verrouillé. Veuillez contacter l'administrateur.",
    too_many_attempts:
      "Trop de tentatives de connexion. Veuillez réessayer plus tard.",
    welcome: "Bienvenue",
    select_option: "Veuillez sélectionner une option",
    borrow_item: "Emprunter un Article",
    return_item: "Retourner un Article",
    admin_panel: "Panneau d'Administration",
    borrow_description:
      "Emprunter des équipements ou outils depuis les casiers disponibles",
    return_description:
      "Retourner les articles empruntés à leurs casiers assignés",
    admin_panel_description:
      "Accéder aux fonctions administratives et à la gestion du système",
    items_description: "Gérer l'inventaire des équipements et outils",
    lockers_description: "Configurer et surveiller le statut des casiers",
    payments_menu_description: "Gérer les paiements et la facturation",
    get_started: "Commencer",
    quick_overview: "Aperçu Rapide",
    follow_steps_borrow: "Suivez les étapes pour emprunter un article",
    authentication: "Authentification",
    choose_authentication_method: "Choisissez votre méthode d'authentification",
    rfid_card: "Carte RFID",
    scan_rfid: "Scanner la Carte RFID",
    scan_rfid_description: "Veuillez scanner votre carte RFID pour continuer",
    simulate_rfid_scan: "Simuler le Scan RFID",
    user_id: "ID Utilisateur",
    enter_user_id: "Entrez votre ID utilisateur",
    enter_user_id_description:
      "Entrez votre ID utilisateur numérique si vous n'avez pas votre carte RFID",
    continue: "Continuer",
    select_item: "Sélectionner l'Article",
    choose_item_borrow: "Choisissez l'article que vous voulez emprunter",
    select_locker: "Sélectionner le Casier",
    select_available_locker:
      "Sélectionnez un casier disponible pour votre article",
    confirm_borrow: "Confirmer l'Emprunt",
    confirm_borrowing_details:
      "Veuillez confirmer les détails de votre emprunt",
    borrow_success: "Article emprunté avec succès",
    borrow_error: "Échec de l'emprunt",
    // Return
    follow_steps_return: "Suivez les étapes pour retourner un article",
    scan_rfid_return_description:
      "Veuillez scanner votre carte RFID pour retourner votre article",
    enter_user_id_return_description:
      "Entrez votre ID utilisateur numérique pour retourner votre article",
    select_item_return: "Sélectionner l'Article à Retourner",
    choose_item_return: "Choisissez l'article que vous voulez retourner",
    confirm_return: "Confirmer le Retour",
    confirm_return_details: "Veuillez confirmer les détails de votre retour",
    return_success: "Article retourné avec succès",
    return_error: "Échec du retour de l'article",
    error_fetching_items:
      "Erreur lors de la récupération des articles empruntés",
    borrowed_on: "Emprunté le",
    back_to_main_menu: "Retour au Menu Principal",
    // Dashboard
    dashboard_description: "Aperçu du Système de Casiers Intelligents",
    // Items Management
    items_management: "Gestion des Articles",
    items_management_description:
      "Gérer les équipements et outils dans le système de casiers",
    search_items: "Rechercher des articles...",
    search_borrowed_items: "Rechercher des articles empruntés...",
    no_items_found: "Aucun article trouvé",
    try_different_search: "Essayez un terme de recherche différent",
    all_lockers: "Tous les Casiers",
    confirm_delete_item: "Êtes-vous sûr de vouloir supprimer cet article ?",
    failed_add_item: "Échec de l'ajout de l'article",
    failed_update_item: "Échec de la mise à jour de l'article",
    failed_delete_item: "Échec de la suppression de l'article",
    // Active Borrows (Emprunts)
    active_borrows: "Emprunts Actifs",
    active_borrows_description:
      "Voir et gérer tous les articles actuellement empruntés",
    active_borrows_menu_description:
      "Voir tous les emprunts actifs et leur statut",
    search_borrows: "Rechercher des emprunts...",
    filter_by_user: "Filtrer par Utilisateur",
    filter_by_item: "Filtrer par Article",
    filter_by_date: "Filtrer par Date",
    all_users: "Tous les Utilisateurs",
    all_items: "Tous les Articles",
    showing: "Affichage de",
    of: "sur",
    duration: "Durée",
    days: "jours",
    hours: "heures",
    less_than_hour: "Moins d'1 heure",
    no_active_borrows: "Aucun Emprunt Actif",
    no_active_borrows_description:
      "Il n'y a actuellement aucun emprunt actif dans le système",
    failed_export_borrows: "Échec de l'exportation des emprunts",
    dashboard: "Tableau de Bord",
    total_users: "Total Utilisateurs",
    total_items: "Total Articles",
    total_lockers: "Total Casiers",
    recent_activity: "Activité Récente",
    loading: "Chargement...",
    error: "Erreur",
    success: "Succès",
    cancel: "Annuler",
    save: "Enregistrer",
    delete: "Supprimer",
    edit: "Modifier",
    add: "Ajouter",
    search: "Rechercher",
    no_data: "Aucune donnée disponible",

    // Registration
    create_account: "Créer votre compte",
    register_description: "Rejoignez le Système de Casiers Intelligents",
    register: "S'inscrire",
    email: "Email",
    first_name: "Prénom",
    last_name: "Nom de famille",
    confirm_password: "Confirmer le mot de passe",
    already_have_account: "Vous avez déjà un compte ?",
    username_placeholder: "Entrez le nom d'utilisateur",
    email_placeholder: "Entrez l'adresse email",
    first_name_placeholder: "Entrez le prénom",
    last_name_placeholder: "Entrez le nom de famille",
    password_placeholder: "Entrez le mot de passe",
    confirm_password_placeholder: "Confirmez votre mot de passe",
    password_requirements: "Exigences du mot de passe :",
    min_8_characters: "Au moins 8 caractères",
    one_uppercase: "Une lettre majuscule",
    one_lowercase: "Une lettre minuscule",
    one_number: "Un chiffre",
    one_special: "Un caractère spécial",
    all_fields_required: "Tous les champs sont requis",
    passwords_dont_match: "Les mots de passe ne correspondent pas",
    password_requirements_not_met:
      "Les exigences du mot de passe ne sont pas respectées",
    invalid_email: "Adresse email invalide",
    registration_successful: "Inscription réussie ! Veuillez vous connecter.",
    registration_failed: "Échec de l'inscription. Veuillez réessayer.",
    student_id: "ID Étudiant",
    student_id_placeholder: "Entrez votre ID étudiant",
    scan_card: "Scanner la Carte",
    scan_card_description: "Ou scannez votre carte d'étudiant",
    generate_test_id: "Générer un ID de Test",

    // Reports
    reports: "Rapports",
    report_type: "Type de Rapport",
    date_range: "Plage de Dates",
    start_date: "Date de Début",
    end_date: "Date de Fin",
    daily: "Quotidien",
    weekly: "Hebdomadaire",
    monthly: "Mensuel",
    yearly: "Annuel",
    transactions: "Transactions",
    export_excel: "Exporter Excel",
    export_pdf: "Exporter PDF",
    generate: "Générer",
    generating: "Génération...",
    summary: "Résumé",
    total_transactions: "Total Transactions",
    borrows: "Emprunts",
    returns: "Retours",
    unique_users: "Utilisateurs Uniques",
    unique_items: "Articles Uniques",
    transaction_details: "Détails des Transactions",
    user: "Utilisateur",
    item: "Article",
    action: "Action",
    timestamp: "Horodatage",
    locker: "Casier",
    overview: "Aperçu",
    quick_actions: "Actions Rapides",
    generate_report: "Générer un Rapport",
    view_transactions: "Voir les transactions et analyses",

    // User Management
    add_user: "Ajouter un utilisateur",
    edit_user: "Modifier l'utilisateur",
    delete_user: "Supprimer l'utilisateur",
    search_users: "Rechercher des utilisateurs...",
    filter_by_role: "Filtrer par rôle",
    all_roles: "Tous les rôles",
    new_password: "Nouveau mot de passe",
    leave_blank: "laisser vide pour conserver l'actuel",
    role: "Rôle",
    student: "Étudiant",
    user_management: "Gestion des utilisateurs",
    manage_accounts: "Gérer les comptes utilisateurs et les permissions",
    no_users_found: "Aucun utilisateur trouvé",
    get_started_adding: "Commencez par ajouter votre premier utilisateur",
    actions: "Actions",
    confirm_delete: "Êtes-vous sûr de vouloir supprimer cet utilisateur ?",
    failed_add_user: "Échec de l'ajout de l'utilisateur",
    failed_update_user: "Échec de la mise à jour de l'utilisateur",
    failed_delete_user: "Échec de la suppression de l'utilisateur",
    save_changes: "Enregistrer les modifications",

    // Lockers
    lockers_management: "Gestion des Casiers",
    lockers_management_description:
      "Gérer les emplacements et statuts des casiers",
    search_lockers: "Rechercher des casiers...",
    all_status: "Tous les Statuts",
    available: "Disponible",
    occupied: "Occupé",
    maintenance: "Maintenance",
    reserved: "Réservé",
    inactive: "Inactif",
    available_lockers: "Casiers Disponibles",
    reserved_lockers: "Casiers Réservés",
    maintenance_lockers: "Casiers en Maintenance",
    inactive_lockers: "Casiers Inactifs",
    no_available_lockers: "Aucun Casier Disponible",
    all_lockers_occupied:
      "Tous les casiers sont actuellement occupés ou en maintenance.",
    locker_with_item: "Casier avec l'Article Sélectionné",
    empty_lockers: "Casiers Vides",
    contains_item: "Contient l'Article",
    no_item: "Aucun Article",
    item_locker_unavailable: "Casier de l'Article Indisponible",
    item_locker_unavailable_desc:
      "Le casier contenant cet article est actuellement indisponible (maintenance, réservé, ou inactif).",
    no_borrowed_items: "Aucun Article Emprunté",
    no_borrowed_items_desc:
      "Vous n'avez actuellement aucun article emprunté. Visitez la page Emprunter pour emprunter des articles.",
    no_lockers_found: "Aucun casier trouvé",
    get_started_adding_locker: "Commencez par ajouter votre premier casier",
    rs485_configuration: "Configuration RS485",
    rs485_address: "Adresse RS485",
    rs485_address_help: "Adresse carte (0-31 dipswitch)",
    rs485_locker_number: "Numéro de Casier",
    rs485_locker_number_help: "Numéro de casier (1-24)",
    rs485_protocol_info:
      "Protocole: 5A5A 00 [ADRESSE] 00 04 00 01 [NUMERO_CASIER] [CHECKSUM]",

    // Logs
    logs_title: "Journaux Système",
    logs_description:
      "Surveiller l'activité du système et les actions des utilisateurs",
    search_logs: "Rechercher dans les journaux...",
    all_actions: "Toutes les Actions",
    filters: "Filtres",
    export_csv: "Exporter CSV",
    clear_filters: "Effacer les filtres",
    no_logs_found: "Aucun journal trouvé",
    try_adjusting_search: "Essayez d'ajuster vos critères de recherche",
    no_activity_logged: "Aucune activité n'a encore été enregistrée",
    unknown_user: "Utilisateur inconnu",
    unknown_item: "Article inconnu",
    unknown_locker: "Casier inconnu",
    just_now: "À l'instant",
    minutes_ago: "minutes",
    hours_ago: "heures",
    failed_export_logs: "Échec de l'exportation des journaux",

    // Payments
    payments: "Paiements",
    payments_description:
      "Gérer les paiements et les informations de facturation",
    search_payments: "Rechercher des paiements...",
    new_payment: "Nouveau Paiement",
    download_excel: "Télécharger Excel",
    add_money: "Ajouter de l'Argent",
    balance: "Solde",
    amount: "Montant",
    description: "Description",
    date: "Date",
    currency: "Devise",
    payment_history: "Historique des Paiements",
    no_payments_found: "Aucun paiement trouvé",
    no_payments_yet: "Aucun paiement n'a encore été effectué",
    failed_add_payment: "Échec de l'ajout du paiement",
    failed_add_money: "Échec de l'ajout d'argent",
    all_statuses: "Tous les Statuts",
    failed: "Échoué",
    show: "Afficher",
    per_page: "par page",
    all: "Tout",
    page: "Page",
    add_locker: "Ajouter un Casier",
    item_name: "Nom de l'Article",
    description_optional: "Description (Optionnel)",
    system_logs: "Journaux Système",
    manage_users: "Gérer les Utilisateurs",
    view_current_borrows: "Voir les articles actuellement empruntés",
    view_activity_logs: "Voir toute l'activité du système",
    add_edit_users: "Ajouter, modifier ou supprimer des utilisateurs",
    my_balance: "Mon solde",
    balance_description:
      "Gérez le solde de votre compte et l'historique des paiements",
    current_balance: "Solde actuel",

    // Reservations
    reservations: "Réservations",
    reservations_menu_description:
      "Gérer et programmer les réservations de casiers",
    "reservations.title": "Réservations",
    "reservations.allStatuses": "Tous les statuts",
    "reservations.active": "Actif",
    "reservations.cancelled": "Annulé",
    "reservations.completed": "Terminé",
    "reservations.expired": "Expiré",
    "reservations.createNew": "Créer une nouvelle réservation",
    "reservations.calendar": "Calendrier",
    "reservations.reservationsFor": "Réservations pour",
    "reservations.allReservations": "Toutes les réservations",
    "reservations.reservationCode": "Code de réservation",
    "reservations.startTime": "Heure de début",
    "reservations.endTime": "Heure de fin",
    "reservations.accessCode": "Code d'accès",
    "reservations.notes": "Notes",
    "reservations.edit": "Modifier",
    "reservations.cancel": "Annuler",
    "reservations.noReservations": "Aucune réservation trouvée",
    "reservations.locker": "Casier",
    "reservations.selectLocker": "Sélectionner un casier",
    "reservations.creating": "Création...",
    "reservations.create": "Créer",
    "reservations.editReservation": "Modifier la réservation",
    "reservations.updating": "Mise à jour...",
    "reservations.update": "Mettre à jour",
    "reservations.confirmCancel":
      "Êtes-vous sûr de vouloir annuler cette réservation ?",
  },
  es: {
    main_menu: "Menú Principal",
    borrow: "Prestar",
    return: "Devolver",
    admin: "Administración",
    users: "Usuarios",
    items: "Artículos",
    lockers: "Casilleros",
    logs: "Registros",
    logout: "Cerrar Sesión",
    login: "Iniciar Sesión",
    username: "Nombre de Usuario",
    password: "Contraseña",
    login_button: "Iniciar Sesión",
    login_error: "Nombre de usuario o contraseña inválidos",
    login_description:
      "Inicia sesión para acceder al Sistema de Casilleros Inteligentes",
    enter_username: "Ingresa tu nombre de usuario",
    enter_password: "Ingresa tu contraseña",
    fill_all_fields: "Por favor completa todos los campos",
    demo_credentials:
      "Credenciales de demostración: admin/admin123, student1/student123, manager/manager123, supervisor/supervisor123",
    dont_have_account: "¿No tienes una cuenta?",
    sign_in: "Iniciar sesión",
    server_error: "Error del servidor. Por favor intenta más tarde.",
    network_error: "Error de red. Por favor verifica tu conexión.",
    login_failed: "Error al iniciar sesión. Por favor intenta de nuevo.",
    invalid_credentials:
      "Nombre de usuario o contraseña inválidos. Por favor intenta de nuevo.",
    account_locked: "Cuenta bloqueada. Por favor contacta al administrador.",
    too_many_attempts:
      "Demasiados intentos de inicio de sesión. Por favor intenta más tarde.",
    welcome: "Bienvenido",
    select_option: "Por favor seleccione una opción",
    borrow_item: "Prestar un Artículo",
    return_item: "Devolver un Artículo",
    admin_panel: "Panel de Administración",
    borrow_description:
      "Prestar equipos o herramientas desde casilleros disponibles",
    return_description:
      "Devolver artículos prestados a sus casilleros asignados",
    admin_panel_description:
      "Acceder a funciones administrativas y gestión del sistema",
    items_description: "Gestionar inventario de equipos y herramientas",
    lockers_description: "Configurar y monitorear el estado de los casilleros",
    payments_menu_description: "Gestionar pagos y facturación",
    get_started: "Comenzar",
    quick_overview: "Vista Rápida",
    follow_steps_borrow: "Sigue los pasos para prestar un artículo",
    authentication: "Autenticación",
    choose_authentication_method: "Elige tu método de autenticación",
    rfid_card: "Tarjeta RFID",
    scan_rfid: "Escanear Tarjeta RFID",
    scan_rfid_description: "Por favor escanea tu tarjeta RFID para continuar",
    simulate_rfid_scan: "Simular Escaneo RFID",
    user_id: "ID de Usuario",
    enter_user_id: "Ingresa tu ID de usuario",
    enter_user_id_description:
      "Ingresa tu ID de usuario numérico si no tienes tu tarjeta RFID",
    continue: "Continuar",
    select_item: "Seleccionar Artículo",
    choose_item_borrow: "Elige el artículo que quieres prestar",
    select_locker: "Seleccionar Casillero",
    select_available_locker:
      "Selecciona un casillero disponible para tu artículo",
    confirm_borrow: "Confirmar Préstamo",
    confirm_borrowing_details: "Por favor confirma los detalles de tu préstamo",
    borrow_success: "Artículo prestado exitosamente",
    borrow_error: "Error al prestar artículo",
    // Return
    follow_steps_return: "Sigue los pasos para devolver un artículo",
    scan_rfid_return_description:
      "Por favor escanea tu tarjeta RFID para devolver tu artículo",
    enter_user_id_return_description:
      "Ingresa tu ID de usuario numérico para devolver tu artículo",
    select_item_return: "Seleccionar Artículo para Devolver",
    choose_item_return: "Elige el artículo que quieres devolver",
    confirm_return: "Confirmar Devolución",
    confirm_return_details: "Por favor confirma los detalles de tu devolución",
    return_success: "Artículo devuelto exitosamente",
    return_error: "Error al devolver artículo",
    error_fetching_items: "Error al obtener artículos prestados",
    borrowed_on: "Prestado el",
    back_to_main_menu: "Volver al Menú Principal",
    // Dashboard
    dashboard_description:
      "Vista general del Sistema de Casilleros Inteligentes",
    // Items Management
    items_management: "Gestión de Artículos",
    items_management_description:
      "Gestionar equipos y herramientas en el sistema de casilleros",
    search_items: "Buscar artículos...",
    all_lockers: "Todos los Casilleros",
    confirm_delete_item: "¿Estás seguro de que quieres eliminar este artículo?",
    failed_add_item: "Error al agregar artículo",
    failed_update_item: "Error al actualizar artículo",
    failed_delete_item: "Error al eliminar artículo",
    // Active Borrows (Emprunts)
    active_borrows: "Préstamos Activos",
    active_borrows_description:
      "Ver y gestionar todos los artículos actualmente prestados",
    active_borrows_menu_description:
      "Ver todos los préstamos activos y su estado",
    search_borrows: "Buscar préstamos...",
    filter_by_user: "Filtrar por Usuario",
    filter_by_item: "Filtrar por Artículo",
    filter_by_date: "Filtrar por Fecha",
    all_users: "Todos los Usuarios",
    all_items: "Todos los Artículos",
    showing: "Mostrando",
    of: "/",
    duration: "Duración",
    days: "días",
    hours: "horas",
    less_than_hour: "Menos de 1 hora",
    no_active_borrows: "No Hay Préstamos Activos",
    no_active_borrows_description:
      "Actualmente no hay préstamos activos en el sistema",
    failed_export_borrows: "Error al exportar préstamos",
    dashboard: "Panel de Control",
    total_users: "Total de Usuarios",
    total_items: "Total de Artículos",
    total_lockers: "Total de Casilleros",
    recent_activity: "Actividad Reciente",
    loading: "Cargando...",
    error: "Error",
    success: "Éxito",
    cancel: "Cancelar",
    save: "Guardar",
    delete: "Eliminar",
    edit: "Editar",
    add: "Agregar",
    search: "Buscar",
    no_data: "No hay datos disponibles",

    // Registration
    create_account: "Crear tu cuenta",
    register_description: "Únete al Sistema de Casilleros Inteligentes",
    register: "Registrarse",
    email: "Correo Electrónico",
    first_name: "Nombre",
    last_name: "Apellido",
    confirm_password: "Confirmar Contraseña",
    already_have_account: "¿Ya tienes una cuenta?",
    username_placeholder: "Ingresa el nombre de usuario",
    email_placeholder: "Ingresa la dirección de correo",
    first_name_placeholder: "Ingresa el nombre",
    last_name_placeholder: "Ingresa el apellido",
    password_placeholder: "Ingresa la contraseña",
    confirm_password_placeholder: "Confirma tu contraseña",
    password_requirements: "Requisitos de la contraseña:",
    min_8_characters: "Al menos 8 caracteres",
    one_uppercase: "Una letra mayúscula",
    one_lowercase: "Una letra minúscula",
    one_number: "Un número",
    one_special: "Un carácter especial",
    all_fields_required: "Todos los campos son requeridos",
    passwords_dont_match: "Las contraseñas no coinciden",
    password_requirements_not_met:
      "No se cumplen los requisitos de la contraseña",
    invalid_email: "Dirección de correo inválida",
    registration_successful: "¡Registro exitoso! Por favor inicia sesión.",
    registration_failed: "Error en el registro. Por favor intenta de nuevo.",
    student_id: "ID de Estudiante",
    student_id_placeholder: "Ingresa tu ID de estudiante",
    scan_card: "Escanear Tarjeta",
    scan_card_description: "O escanea tu tarjeta de estudiante",
    generate_test_id: "Generar ID de Prueba",

    // Reports
    reports: "Reportes",
    report_type: "Tipo de Reporte",
    date_range: "Rango de Fechas",
    start_date: "Fecha de Inicio",
    end_date: "Fecha de Fin",
    daily: "Diario",
    weekly: "Semanal",
    monthly: "Mensual",
    yearly: "Anual",
    transactions: "Transacciones",
    export_excel: "Exportar Excel",
    export_pdf: "Exportar PDF",
    generate: "Generar",
    generating: "Generando...",
    summary: "Resumen",
    total_transactions: "Total de Transacciones",
    borrows: "Préstamos",
    returns: "Devoluciones",
    unique_users: "Usuarios Únicos",
    unique_items: "Artículos Únicos",
    transaction_details: "Detalles de Transacciones",
    user: "Usuario",
    item: "Artículo",
    action: "Acción",
    timestamp: "Marca de Tiempo",
    locker: "Casillero",
    overview: "Resumen",
    quick_actions: "Acciones Rápidas",
    generate_report: "Generar Reporte",
    view_transactions: "Ver transacciones y análisis",

    // User Management
    add_user: "Agregar Usuario",
    edit_user: "Editar Usuario",
    delete_user: "Eliminar Usuario",
    search_users: "Buscar usuarios...",
    filter_by_role: "Filtrar por rol",
    all_roles: "Todos los Roles",
    new_password: "Nueva Contraseña",
    leave_blank: "dejar en blanco para mantener la actual",
    role: "Rol",
    student: "Estudiante",
    user_management: "Gestión de Usuarios",
    manage_accounts: "Gestionar cuentas de usuario y permisos",
    no_users_found: "No se encontraron usuarios",
    get_started_adding: "Comienza agregando tu primer usuario",
    actions: "Acciones",
    confirm_delete: "¿Estás seguro de que quieres eliminar este usuario?",
    failed_add_user: "Error al agregar usuario",
    failed_update_user: "Error al actualizar usuario",
    failed_delete_user: "Error al eliminar usuario",
    save_changes: "Guardar Cambios",

    // Lockers
    lockers_management: "Gestión de Casilleros",
    lockers_management_description:
      "Gestionar ubicaciones y estado de casilleros",
    search_lockers: "Buscar casilleros...",
    all_status: "Todos los Estados",
    available: "Disponible",
    occupied: "Ocupado",
    maintenance: "Mantenimiento",
    reserved: "Reservado",
    inactive: "Inactivo",
    available_lockers: "Casilleros Disponibles",
    reserved_lockers: "Casilleros Reservados",
    maintenance_lockers: "Casilleros en Mantenimiento",
    inactive_lockers: "Casilleros Inactivos",
    no_available_lockers: "No Hay Casilleros Disponibles",
    all_lockers_occupied:
      "Todos los casilleros están actualmente ocupados o en mantenimiento.",
    locker_with_item: "Casillero con Artículo Seleccionado",
    empty_lockers: "Casilleros Vacíos",
    contains_item: "Contiene Artículo",
    no_item: "Sin Artículo",
    item_locker_unavailable: "Casillero del Artículo No Disponible",
    item_locker_unavailable_desc:
      "El casillero que contiene este artículo está actualmente no disponible (mantenimiento, reservado, o inactivo).",
    no_borrowed_items: "No Hay Artículos Prestados",
    no_borrowed_items_desc:
      "Actualmente no tienes artículos prestados. Visita la página Prestar para prestar artículos.",
    no_lockers_found: "No se encontraron casilleros",
    get_started_adding_locker: "Comienza agregando tu primer casillero",
    rs485_configuration: "Configuración RS485",
    rs485_address: "Dirección RS485",
    rs485_address_help: "Dirección de tarjeta (0-31 dipswitch)",
    rs485_locker_number: "Número de Casillero",
    rs485_locker_number_help: "Número de casillero (1-24)",
    rs485_protocol_info:
      "Protocolo: 5A5A 00 [DIRECCION] 00 04 00 01 [NUMERO_CASILLERO] [CHECKSUM]",

    // Logs
    logs_title: "Registros del Sistema",
    logs_description:
      "Monitorear la actividad del sistema y las acciones de los usuarios",
    search_logs: "Buscar en registros...",
    all_actions: "Todas las Acciones",
    filters: "Filtros",
    export_csv: "Exportar CSV",
    clear_filters: "Limpiar Filtros",
    no_logs_found: "No se encontraron registros",
    try_adjusting_search: "Intenta ajustar tus criterios de búsqueda",
    no_activity_logged: "No se ha registrado actividad aún",
    unknown_user: "Usuario desconocido",
    unknown_item: "Artículo desconocido",
    unknown_locker: "Casillero desconocido",
    just_now: "Ahora mismo",
    minutes_ago: "minutos",
    hours_ago: "horas",
    failed_export_logs: "Error al exportar registros",

    // Payments
    payments: "Pagos",
    payments_description: "Gestionar pagos e información de facturación",
    search_payments: "Buscar pagos...",
    new_payment: "Nuevo Pago",
    download_excel: "Descargar Excel",
    add_money: "Agregar Dinero",
    balance: "Saldo",
    amount: "Monto",
    description: "Descripción",
    date: "Fecha",
    currency: "Moneda",
    payment_history: "Historial de Pagos",
    no_payments_found: "No se encontraron pagos",
    no_payments_yet: "Aún no se han realizado pagos",
    failed_add_payment: "Error al agregar pago",
    failed_add_money: "Error al agregar dinero",
    all_statuses: "Todos los Estados",
    failed: "Fallido",
    show: "Mostrar",
    per_page: "por página",
    all: "Todas",
    page: "Página",
    add_locker: "Agregar Casillero",
    item_name: "Nombre del Artículo",
    description_optional: "Descripción (Opcional)",
    system_logs: "Registros del Sistema",
    manage_users: "Gestionar Usuarios",
    view_current_borrows: "Ver artículos actualmente prestados",
    view_activity_logs: "Ver toda la actividad del sistema",
    add_edit_users: "Agregar, editar o eliminar usuarios",
    my_balance: "Mi saldo",
    balance_description:
      "Gestiona el saldo de tu cuenta y el historial de pagos",
    current_balance: "Saldo actual",

    // Reservations
    reservations: "Reservas",
    reservations_menu_description:
      "Gestionar y programar reservas de casilleros",
    "reservations.title": "Reservas",
    "reservations.allStatuses": "Todos los estados",
    "reservations.active": "Activo",
    "reservations.cancelled": "Cancelado",
    "reservations.completed": "Completado",
    "reservations.expired": "Expirado",
    "reservations.createNew": "Crear nueva reserva",
    "reservations.calendar": "Calendario",
    "reservations.reservationsFor": "Reservas para",
    "reservations.allReservations": "Todas las reservas",
    "reservations.reservationCode": "Código de reserva",
    "reservations.startTime": "Hora de inicio",
    "reservations.endTime": "Hora de fin",
    "reservations.accessCode": "Código de acceso",
    "reservations.notes": "Notas",
    "reservations.edit": "Editar",
    "reservations.cancel": "Cancelar",
    "reservations.noReservations": "No se encontraron reservas",
    "reservations.locker": "Casillero",
    "reservations.selectLocker": "Seleccionar casillero",
    "reservations.creating": "Creando...",
    "reservations.create": "Crear",
    "reservations.editReservation": "Editar reserva",
    "reservations.updating": "Actualizando...",
    "reservations.update": "Actualizar",
    "reservations.confirmCancel":
      "¿Estás seguro de que quieres cancelar esta reserva?",
  },
  tr: {
    main_menu: "Ana Menü",
    borrow: "Ödünç Al",
    return: "Geri Ver",
    admin: "Yönetim",
    users: "Kullanıcılar",
    items: "Eşyalar",
    lockers: "Dolaplar",
    logs: "Kayıtlar",
    logout: "Çıkış",
    login: "Giriş",
    username: "Kullanıcı Adı",
    password: "Şifre",
    login_button: "Giriş Yap",
    login_error: "Geçersiz kullanıcı adı veya şifre",
    login_description: "Akıllı Dolap Sistemine erişmek için giriş yapın",
    enter_username: "Kullanıcı adınızı girin",
    enter_password: "Şifrenizi girin",
    fill_all_fields: "Lütfen tüm alanları doldurun",
    demo_credentials:
      "Demo kimlik bilgileri: admin/admin123, student1/student123, manager/manager123, supervisor/supervisor123",
    dont_have_account: "Hesabınız yok mu?",
    sign_in: "Giriş yap",
    server_error: "Sunucu hatası. Lütfen daha sonra tekrar deneyin.",
    network_error: "Ağ hatası. Lütfen bağlantınızı kontrol edin.",
    login_failed: "Giriş başarısız. Lütfen tekrar deneyin.",
    invalid_credentials:
      "Geçersiz kullanıcı adı veya şifre. Lütfen tekrar deneyin.",
    account_locked: "Hesap kilitli. Lütfen yönetici ile iletişime geçin.",
    too_many_attempts:
      "Çok fazla giriş denemesi. Lütfen daha sonra tekrar deneyin.",
    welcome: "Hoş Geldiniz",
    select_option: "Lütfen bir seçenek seçin",
    borrow_item: "Eşya Ödünç Al",
    return_item: "Eşya Geri Ver",
    admin_panel: "Yönetim Paneli",
    borrow_description: "Mevcut dolaplardan ekipman veya araçlar ödünç alın",
    return_description: "Ödünç alınan eşyaları atanmış dolaplarına geri verin",
    admin_panel_description: "Yönetim işlevlerine ve sistem yönetimine erişin",
    items_description: "Ekipman ve araç envanterini yönetin",
    lockers_description: "Dolap durumunu yapılandırın ve izleyin",
    payments_menu_description: "Ödemeleri ve faturalandırmayı yönetin",
    get_started: "Başla",
    quick_overview: "Hızlı Genel Bakış",
    follow_steps_borrow: "Eşya ödünç almak için adımları takip edin",
    authentication: "Kimlik Doğrulama",
    choose_authentication_method: "Kimlik doğrulama yönteminizi seçin",
    rfid_card: "RFID Kartı",
    scan_rfid: "RFID Kartı Tara",
    scan_rfid_description: "Devam etmek için RFID kartınızı tarayın",
    simulate_rfid_scan: "RFID Taramasını Simüle Et",
    user_id: "Kullanıcı ID",
    enter_user_id: "Kullanıcı ID'nizi girin",
    enter_user_id_description:
      "RFID kartınız yoksa sayısal kullanıcı ID'nizi girin",
    continue: "Devam Et",
    select_item: "Eşya Seç",
    choose_item_borrow: "Ödünç almak istediğiniz eşyayı seçin",
    select_locker: "Dolap Seç",
    select_available_locker: "Eşyanız için mevcut bir dolap seçin",
    confirm_borrow: "Ödünç Almayı Onayla",
    confirm_borrowing_details: "Lütfen ödünç alma detaylarınızı onaylayın",
    borrow_success: "Eşya başarıyla ödünç alındı",
    borrow_error: "Eşya ödünç alınamadı",
    // Return
    follow_steps_return: "Eşya iade etmek için adımları takip edin",
    scan_rfid_return_description:
      "Eşyanızı iade etmek için RFID kartınızı tarayın",
    enter_user_id_return_description:
      "Eşyanızı iade etmek için sayısal kullanıcı ID'nizi girin",
    select_item_return: "İade Edilecek Eşyayı Seç",
    choose_item_return: "İade etmek istediğiniz eşyayı seçin",
    confirm_return: "İadeyi Onayla",
    confirm_return_details: "Lütfen iade detaylarınızı onaylayın",
    return_success: "Eşya başarıyla iade edildi",
    return_error: "Eşya iade edilemedi",
    error_fetching_items: "Ödünç alınan eşyalar alınırken hata oluştu",
    borrowed_on: "Ödünç alınma tarihi",
    back_to_main_menu: "Ana Menüye Dön",
    // Dashboard
    dashboard_description: "Akıllı Dolap Sisteminin Genel Bakışı",
    // Items Management
    items_management: "Eşya Yönetimi",
    items_management_description:
      "Dolap sistemindeki ekipman ve araçları yönetin",
    search_items: "Eşya ara...",
    all_lockers: "Tüm Dolaplar",
    confirm_delete_item: "Bu eşyayı silmek istediğinizden emin misiniz?",
    failed_add_item: "Eşya eklenemedi",
    failed_update_item: "Eşya güncellenemedi",
    failed_delete_item: "Eşya silinemedi",
    // Active Borrows (Emprunts)
    active_borrows: "Aktif Ödünç Almalar",
    active_borrows_description:
      "Şu anda ödünç alınan tüm eşyaları görüntüleyin ve yönetin",
    active_borrows_menu_description:
      "Tüm aktif ödünç almaları ve durumlarını görüntüleyin",
    search_borrows: "Ödünç almaları ara...",
    filter_by_user: "Kullanıcıya Göre Filtrele",
    filter_by_item: "Eşyaya Göre Filtrele",
    filter_by_date: "Tarihe Göre Filtrele",
    all_users: "Tüm Kullanıcılar",
    all_items: "Tüm Eşyalar",
    showing: "Gösteriliyor",
    of: "/",
    duration: "Süre",
    days: "gün",
    hours: "saat",
    less_than_hour: "1 saatten az",
    no_active_borrows: "Aktif Ödünç Alma Yok",
    no_active_borrows_description:
      "Sistemde şu anda aktif ödünç alma bulunmuyor",
    failed_export_borrows: "Ödünç almalar dışa aktarılamadı",
    dashboard: "Kontrol Paneli",
    total_users: "Toplam Kullanıcı",
    total_items: "Toplam Eşya",
    total_lockers: "Toplam Dolap",
    recent_activity: "Son Aktiviteler",
    loading: "Yükleniyor...",
    error: "Hata",
    success: "Başarılı",
    cancel: "İptal",
    save: "Kaydet",
    delete: "Sil",
    edit: "Düzenle",
    add: "Ekle",
    search: "Ara",
    no_data: "Veri bulunamadı",

    // Registration
    create_account: "Hesabınızı oluşturun",
    register_description: "Akıllı Dolap Sistemine katılın",
    register: "Kayıt Ol",
    email: "E-posta",
    first_name: "Ad",
    last_name: "Soyad",
    confirm_password: "Şifreyi Onayla",
    already_have_account: "Zaten hesabınız var mı?",
    username_placeholder: "Kullanıcı adını girin",
    email_placeholder: "E-posta adresini girin",
    first_name_placeholder: "Adınızı girin",
    last_name_placeholder: "Soyadınızı girin",
    password_placeholder: "Şifrenizi girin",
    confirm_password_placeholder: "Şifrenizi onaylayın",
    password_requirements: "Şifre gereksinimleri:",
    min_8_characters: "En az 8 karakter",
    one_uppercase: "Bir büyük harf",
    one_lowercase: "Bir küçük harf",
    one_number: "Bir rakam",
    one_special: "Bir özel karakter",
    all_fields_required: "Tüm alanlar gereklidir",
    passwords_dont_match: "Şifreler eşleşmiyor",
    password_requirements_not_met: "Şifre gereksinimleri karşılanmıyor",
    invalid_email: "Geçersiz e-posta adresi",
    registration_successful: "Kayıt başarılı! Lütfen giriş yapın.",
    registration_failed: "Kayıt başarısız. Lütfen tekrar deneyin.",
    student_id: "Öğrenci ID",
    student_id_placeholder: "Öğrenci ID'nizi girin",
    scan_card: "Kartı Tara",
    scan_card_description: "Veya öğrenci kartınızı tarayın",
    generate_test_id: "Test ID Oluştur",

    // Reports
    reports: "Raporlar",
    report_type: "Rapor Türü",
    date_range: "Tarih Aralığı",
    start_date: "Başlangıç Tarihi",
    end_date: "Bitiş Tarihi",
    daily: "Günlük",
    weekly: "Haftalık",
    monthly: "Aylık",
    yearly: "Yıllık",
    transactions: "İşlemler",
    export_excel: "Excel'e Aktar",
    export_pdf: "PDF'e Aktar",
    generate: "Oluştur",
    generating: "Oluşturuluyor...",
    summary: "Özet",
    total_transactions: "Toplam İşlem",
    borrows: "Ödünç Almalar",
    returns: "Geri Vermeler",
    unique_users: "Benzersiz Kullanıcılar",
    unique_items: "Benzersiz Eşyalar",
    transaction_details: "İşlem Detayları",
    user: "Kullanıcı",
    item: "Eşya",
    action: "İşlem",
    timestamp: "Zaman Damgası",
    locker: "Dolap",
    overview: "Genel Bakış",
    quick_actions: "Hızlı İşlemler",
    generate_report: "Rapor Oluştur",
    view_transactions: "İşlemleri ve analizleri görüntüle",

    // User Management
    add_user: "Kullanıcı Ekle",
    edit_user: "Kullanıcı Düzenle",
    delete_user: "Kullanıcı Sil",
    search_users: "Kullanıcı ara...",
    filter_by_role: "Rol ile filtrele",
    all_roles: "Tüm Roller",
    new_password: "Yeni Şifre",
    leave_blank: "mevcut şifreyi korumak için boş bırakın",
    role: "Rol",
    student: "Öğrenci",
    user_management: "Kullanıcı Yönetimi",
    manage_accounts: "Kullanıcı hesaplarını ve izinleri yönet",
    no_users_found: "Kullanıcı bulunamadı",
    get_started_adding: "İlk kullanıcınızı ekleyerek başlayın",
    actions: "İşlemler",
    confirm_delete: "Bu kullanıcıyı silmek istediğinizden emin misiniz?",
    failed_add_user: "Kullanıcı eklenemedi",
    failed_update_user: "Kullanıcı güncellenemedi",
    failed_delete_user: "Kullanıcı silinemedi",
    save_changes: "Değişiklikleri Kaydet",

    // Lockers
    lockers_management: "Dolap Yönetimi",
    lockers_management_description: "Dolap konumlarını ve durumunu yönetin",
    search_lockers: "Dolap ara...",
    all_status: "Tüm Durumlar",
    available: "Mevcut",
    occupied: "Dolu",
    maintenance: "Bakım",
    no_lockers_found: "Dolap bulunamadı",
    get_started_adding_locker: "İlk dolabınızı ekleyerek başlayın",
    rs485_configuration: "RS485 Yapılandırması",
    rs485_address: "RS485 Adresi",
    rs485_address_help: "Kart adresi (0-31 dipswitch)",
    rs485_locker_number: "Dolap Numarası",
    rs485_locker_number_help: "Dolap numarası (1-24)",
    rs485_protocol_info:
      "Protokol: 5A5A 00 [ADRES] 00 04 00 01 [DOLAP_NUMARASI] [CHECKSUM]",

    // Logs
    logs_title: "Sistem Kayıtları",
    logs_description: "Sistem aktivitesini ve kullanıcı eylemlerini izleyin",
    search_logs: "Kayıtlarda ara...",
    all_actions: "Tüm İşlemler",
    filters: "Filtreler",
    export_csv: "Exportar CSV",
    clear_filters: "Filtreleri Temizle",
    no_logs_found: "Kayıt bulunamadı",
    try_adjusting_search: "Arama kriterlerinizi ayarlamayı deneyin",
    no_activity_logged: "Henüz hiç aktivite kaydedilmemiş",
    unknown_user: "Bilinmeyen Kullanıcı",
    unknown_item: "Bilinmeyen Eşya",
    unknown_locker: "Bilinmeyen Dolap",
    just_now: "Şimdi",
    minutes_ago: "dakika önce",
    hours_ago: "saat önce",
    failed_export_logs: "Kayıtlar dışa aktarılamadı",

    // Payments
    payments: "Ödemeler",
    payments_description: "Ödemeleri ve faturalandırmayı yönetin",
    search_payments: "Ödeme ara...",
    new_payment: "Yeni Ödeme",
    download_excel: "Excel İndir",
    add_money: "Para Ekle",
    balance: "Bakiye",
    amount: "Miktar",
    description: "Açıklama",
    date: "Tarih",
    currency: "Moneda",
    payment_history: "Ödeme Geçmişi",
    no_payments_found: "Ödeme bulunamadı",
    no_payments_yet: "Henüz ödeme yapılmamış",
    failed_add_payment: "Ödeme eklenemedi",
    failed_add_money: "Para eklenemedi",
    all_statuses: "Tüm Durumlar",
    failed: "Başarısız",
    show: "Göster",
    per_page: "sayfa başına",
    all: "Tümü",
    page: "Sayfa",
    add_locker: "Dolap Ekle",
    item_name: "Eşya Adı",
    description_optional: "Açıklama (İsteğe Bağlı)",
    system_logs: "Sistem Kayıtları",
    manage_users: "Kullanıcıları Yönet",
    view_current_borrows: "Şu anda ödünç alınan eşyaları görüntüle",
    view_activity_logs: "Tüm sistem aktivitesini görüntüle",
    add_edit_users: "Kullanıcı ekle, düzenle veya kaldır",
    my_balance: "Bakiyem",
    balance_description: "Hesap bakiyenizi ve ödeme geçmişinizi yönetin",
    current_balance: "Güncel Bakiye",

    // Reservations
    reservations: "Rezervasyonlar",
    reservations_menu_description:
      "Dolap rezervasyonlarını yönetin ve programlayın",
    "reservations.title": "Rezervasyonlar",
    "reservations.allStatuses": "Tüm durumlar",
    "reservations.active": "Aktif",
    "reservations.cancelled": "İptal edildi",
    "reservations.completed": "Tamamlandı",
    "reservations.expired": "Süresi doldu",
    "reservations.createNew": "Yeni rezervasyon oluştur",
    "reservations.calendar": "Takvim",
    "reservations.reservationsFor": "Rezervasyonlar",
    "reservations.allReservations": "Tüm rezervasyonlar",
    "reservations.reservationCode": "Rezervasyon kodu",
    "reservations.startTime": "Başlangıç zamanı",
    "reservations.endTime": "Bitiş zamanı",
    "reservations.accessCode": "Erişim kodu",
    "reservations.notes": "Notlar",
    "reservations.edit": "Düzenle",
    "reservations.cancel": "İptal",
    "reservations.noReservations": "Rezervasyon bulunamadı",
    "reservations.locker": "Dolap",
    "reservations.selectLocker": "Dolap seçin",
    "reservations.creating": "Oluşturuluyor...",
    "reservations.create": "Oluştur",
    "reservations.editReservation": "Rezervasyonu düzenle",
    "reservations.updating": "Güncelleniyor...",
    "reservations.update": "Güncelle",
    "reservations.confirmCancel":
      "Bu rezervasyonu iptal etmek istediğinizden emin misiniz?",
  },
  "pt-BR": {
    // Navigation
    main_menu: "Menu Principal",
    borrow: "Emprestar",
    return: "Devolver",
    admin: "Administração",
    users: "Usuários",
    items: "Itens",
    lockers: "Armários",
    logs: "Registros",
    logout: "Sair",

    // Login
    login: "Entrar",
    username: "Nome de usuário",
    password: "Senha",
    login_button: "Entrar",
    login_error: "Nome de usuário ou senha inválidos",
    login_description: "Entre para acessar o Sistema de Armários Inteligentes",
    enter_username: "Digite seu nome de usuário",
    enter_password: "Digite sua senha",
    fill_all_fields: "Por favor, preencha todos os campos",
    demo_credentials:
      "Credenciais de demonstração: admin/admin123, student1/student123, manager/manager123, supervisor/supervisor123",
    dont_have_account: "Não tem uma conta?",
    sign_in: "Entrar",
    server_error: "Erro do servidor. Tente novamente mais tarde.",
    network_error: "Erro de rede. Verifique sua conexão.",
    login_failed: "Falha no login. Tente novamente.",
    invalid_credentials: "Nome de usuário ou senha inválidos. Tente novamente.",
    account_locked: "Conta bloqueada. Entre em contato com o administrador.",
    too_many_attempts:
      "Muitas tentativas de login. Tente novamente mais tarde.",

    // Main Menu
    welcome: "Bem-vindo",
    select_option: "Por favor, selecione uma opção",
    borrow_item: "Emprestar um Item",
    return_item: "Devolver um Item",
    admin_panel: "Painel Administrativo",
    borrow_description:
      "Empreste equipamentos ou ferramentas dos armários disponíveis",
    return_description:
      "Devolva itens emprestados aos seus armários designados",
    admin_panel_description:
      "Acesse funções administrativas e gerenciamento do sistema",
    items_description: "Gerencie inventário de equipamentos e ferramentas",
    lockers_description: "Configure e monitore o status dos armários",
    payments_menu_description: "Gerencie pagamentos e informações de cobrança",
    get_started: "Começar",
    quick_overview: "Visão Geral Rápida",

    // Borrow
    follow_steps_borrow: "Siga os passos para emprestar um item",
    authentication: "Autenticação",
    choose_authentication_method: "Escolha seu método de autenticação",
    rfid_card: "Cartão RFID",
    scan_rfid: "Escanear Cartão RFID",
    scan_rfid_description: "Por favor, escaneie seu cartão RFID para continuar",
    simulate_rfid_scan: "Simular Escaneamento RFID",
    user_id: "ID do Usuário",
    enter_user_id: "Digite seu ID de usuário",
    enter_user_id_description:
      "Digite seu ID numérico de usuário se não tiver seu cartão RFID",
    continue: "Continuar",
    select_item: "Selecionar Item",
    choose_item_borrow: "Escolha o item que deseja emprestar",
    select_locker: "Selecionar Armário",
    select_available_locker: "Selecione um armário disponível para seu item",
    confirm_borrow: "Confirmar Empréstimo",
    confirm_borrowing_details:
      "Por favor, confirme os detalhes do seu empréstimo",
    borrow_success: "Item emprestado com sucesso",
    borrow_error: "Falha ao emprestar item",

    // Return
    follow_steps_return: "Siga os passos para devolver um item",
    scan_rfid_return_description:
      "Por favor, escaneie seu cartão RFID para devolver seu item",
    enter_user_id_return_description:
      "Digite seu ID numérico de usuário para devolver seu item",
    select_item_return: "Selecionar Item para Devolver",
    choose_item_return: "Escolha o item que deseja devolver",
    confirm_return: "Confirmar Devolução",
    confirm_return_details: "Por favor, confirme os detalhes da sua devolução",
    return_success: "Item devolvido com sucesso",
    return_error: "Falha ao devolver item",
    error_fetching_items: "Erro ao buscar itens emprestados",
    borrowed_on: "Emprestado em",
    back_to_main_menu: "Voltar ao Menu Principal",

    // Dashboard
    dashboard_description: "Visão geral do Sistema de Armários Inteligentes",

    // Items Management
    items_management: "Gerenciamento de Itens",
    items_management_description:
      "Gerencie equipamentos e ferramentas no sistema de armários",
    search_items: "Buscar itens...",
    search_borrowed_items: "Buscar itens emprestados...",
    no_items_found: "Nenhum item encontrado",
    try_different_search: "Tente um termo de busca diferente",
    all_lockers: "Todos os Armários",
    add_item: "Adicionar Item",
    edit_item: "Editar Item",
    delete_item: "Excluir Item",
    confirm_delete_item: "Tem certeza de que deseja excluir este item?",
    failed_add_item: "Falha ao adicionar item",
    failed_update_item: "Falha ao atualizar item",
    failed_delete_item: "Falha ao excluir item",

    // Active Borrows (Emprunts)
    active_borrows: "Empréstimos Ativos",
    active_borrows_description:
      "Visualize e gerencie todos os itens atualmente emprestados",
    active_borrows_menu_description:
      "Visualize todos os empréstimos ativos e seus status",
    search_borrows: "Buscar empréstimos...",
    filter_by_user: "Filtrar por Usuário",
    filter_by_item: "Filtrar por Item",
    filter_by_date: "Filtrar por Data",
    all_users: "Todos os Usuários",
    all_items: "Todos os Itens",
    showing: "Mostrando",
    of: "de",
    duration: "Duração",
    days: "dias",
    hours: "horas",
    less_than_hour: "Menos de 1 hora",
    no_active_borrows: "Nenhum Empréstimo Ativo",
    no_active_borrows_description:
      "Atualmente não há empréstimos ativos no sistema",
    failed_export_borrows: "Falha ao exportar empréstimos",

    // Admin
    dashboard: "Painel de Controle",
    total_users: "Total de Usuários",
    total_items: "Total de Itens",
    total_lockers: "Total de Armários",
    recent_activity: "Atividade Recente",
    view_current_borrows: "Visualizar itens atualmente emprestados",
    view_activity_logs: "Visualizar toda a atividade do sistema",
    add_edit_users: "Adicionar, editar ou remover usuários",
    completed: "Concluído",
    unknown: "Desconhecido",

    // Common
    loading: "Carregando...",
    error: "Erro",
    success: "Sucesso",
    cancel: "Cancelar",
    save: "Salvar",
    delete: "Excluir",
    edit: "Editar",
    add: "Adicionar",
    search: "Buscar",
    no_data: "Nenhum dado disponível",

    // Registration
    create_account: "Criar sua conta",
    register_description: "Junte-se ao Sistema de Armários Inteligentes",
    register: "Registrar",
    email: "Email",
    first_name: "Nome",
    last_name: "Sobrenome",
    confirm_password: "Confirmar Senha",
    already_have_account: "Já tem uma conta?",
    username_placeholder: "Digite o nome de usuário",
    email_placeholder: "Digite o endereço de email",
    first_name_placeholder: "Digite o nome",
    last_name_placeholder: "Digite o sobrenome",
    password_placeholder: "Digite a senha",
    confirm_password_placeholder: "Confirme sua senha",
    password_requirements: "Requisitos da senha:",
    min_8_characters: "Pelo menos 8 caracteres",
    one_uppercase: "Uma letra maiúscula",
    one_lowercase: "Uma letra minúscula",
    one_number: "Um número",
    one_special: "Um caractere especial",
    all_fields_required: "Todos os campos são obrigatórios",
    passwords_dont_match: "As senhas não coincidem",
    password_requirements_not_met: "Requisitos da senha não atendidos",
    invalid_email: "Endereço de email inválido",
    registration_successful: "Registro bem-sucedido! Por favor, faça login.",
    registration_failed: "Falha no registro. Tente novamente.",
    student_id: "ID do Estudante",
    student_id_placeholder: "Digite seu ID de estudante",
    scan_card: "Escanear Cartão",
    scan_card_description: "Ou escaneie seu cartão de estudante",
    generate_test_id: "Gerar ID de Teste",

    // User Management
    add_user: "Adicionar Usuário",
    edit_user: "Editar Usuário",
    delete_user: "Excluir Usuário",
    search_users: "Buscar usuários...",
    filter_by_role: "Filtrar por função",
    all_roles: "Todas as Funções",
    new_password: "Nova Senha",
    leave_blank: "deixe em branco para manter a atual",
    role: "Função",
    student: "Estudante",
    user_management: "Gerenciamento de Usuários",
    manage_accounts: "Gerencie contas de usuário e permissões",
    no_users_found: "Nenhum usuário encontrado",
    get_started_adding: "Comece adicionando seu primeiro usuário",
    user: "Usuário",
    actions: "Ações",
    confirm_delete: "Tem certeza de que deseja excluir este usuário?",
    failed_add_user: "Falha ao adicionar usuário",
    failed_update_user: "Falha ao atualizar usuário",
    failed_delete_user: "Falha ao excluir usuário",
    save_changes: "Salvar Alterações",

    // Reports
    reports: "Relatórios",
    report_type: "Tipo de Relatório",
    date_range: "Intervalo de Datas",
    start_date: "Data de Início",
    end_date: "Data de Fim",
    daily: "Diário",
    weekly: "Semanal",
    monthly: "Mensal",
    yearly: "Anual",
    transactions: "Transações",
    export_excel: "Exportar Excel",
    export_pdf: "Exportar PDF",
    generate: "Gerar",
    generating: "Gerando...",
    summary: "Resumo",
    total_transactions: "Total de Transações",
    borrows: "Empréstimos",
    returns: "Devoluções",
    unique_users: "Usuários Únicos",
    unique_items: "Itens Únicos",
    transaction_details: "Detalhes da Transação",
    action: "Ação",
    timestamp: "Timestamp",
    locker: "Armário",
    overview: "Visão Geral",
    quick_actions: "Ações Rápidas",
    generate_report: "Gerar Relatório",
    view_transactions: "Visualizar transações e análises",

    // Lockers
    lockers_management: "Gerenciamento de Armários",
    edit_locker: "Editar Armário",
    locker_name: "Nome do Armário",
    location: "Localização",
    status: "Status",
    available: "Disponível",
    occupied: "Ocupado",
    maintenance: "Manutenção",
    reserved: "Reservado",
    inactive: "Inativo",
    available_lockers: "Armários Disponíveis",
    reserved_lockers: "Armários Reservados",
    maintenance_lockers: "Armários em Manutenção",
    inactive_lockers: "Armários Inativos",
    no_available_lockers: "Nenhum Armário Disponível",
    all_lockers_occupied:
      "Todos os armários estão atualmente ocupados ou em manutenção.",
    locker_with_item: "Armário com Item Selecionado",
    empty_lockers: "Armários Vazios",
    contains_item: "Contém Item",
    no_item: "Nenhum Item",
    item_locker_unavailable: "Armário do Item Indisponível",
    item_locker_unavailable_desc:
      "O armário contendo este item está atualmente indisponível (manutenção, reservado ou inativo).",
    no_borrowed_items: "Nenhum Item Emprestado",
    no_borrowed_items_desc:
      "Você não tem nenhum item atualmente emprestado. Visite a página Emprestar para emprestar itens.",
    lockers_management_description:
      "Gerencie localizações e status dos armários",
    search_lockers: "Buscar armários...",
    all_status: "Todos os Status",
    no_lockers_found: "Nenhum armário encontrado",
    get_started_adding_locker: "Comece adicionando seu primeiro armário",
    rs485_configuration: "Configuração RS485",
    rs485_address: "Endereço RS485",
    rs485_address_help: "Endereço do cartão (0-31 dipswitch)",
    rs485_locker_number: "Número do Armário",
    rs485_locker_number_help: "Número do armário (1-24)",
    rs485_protocol_info:
      "Protocolo: 5A5A 00 [ENDEREÇO] 00 04 00 01 [NUMERO_ARMARIO] [CHECKSUM]",

    // Logs
    logs_title: "Registros do Sistema",
    logs_description: "Monitore a atividade do sistema e ações dos usuários",
    search_logs: "Buscar registros...",
    all_actions: "Todas as Ações",
    filters: "Filtros",
    export_csv: "Exportar CSV",
    clear_filters: "Limpar Filtros",
    no_logs_found: "Nenhum registro encontrado",
    try_adjusting_search: "Tente ajustar sua busca ou critérios de filtro",
    no_activity_logged: "Nenhuma atividade foi registrada ainda",
    unknown_user: "Usuário Desconhecido",
    unknown_item: "Item Desconhecido",
    unknown_locker: "Armário Desconhecido",
    just_now: "Agora mesmo",
    minutes_ago: "minutos atrás",
    hours_ago: "horas atrás",
    failed_export_logs: "Falha ao exportar registros",

    // Payments
    payments: "Pagamentos",
    payments_description: "Gerencie pagamentos e informações de cobrança",
    search_payments: "Buscar pagamentos...",
    new_payment: "Novo Pagamento",
    download_excel: "Baixar Excel",
    add_money: "Adicionar Dinheiro",
    balance: "Saldo",
    amount: "Valor",
    description: "Descrição",
    date: "Data",
    currency: "Moeda",
    payment_history: "Histórico de Pagamentos",
    no_payments_found: "Nenhum pagamento encontrado",
    no_payments_yet: "Nenhum pagamento foi feito ainda",
    failed_add_payment: "Falha ao adicionar pagamento",
    failed_add_money: "Falha ao adicionar dinheiro",
    all_statuses: "Todos os Status",
    failed: "Falhou",
    show: "Mostrar",
    per_page: "por página",
    all: "Todos",
    page: "Página",
    add_locker: "Adicionar Armário",
    item_name: "Nome do Item",
    description_optional: "Descrição (Opcional)",
    system_logs: "Registros do Sistema",
    manage_users: "Gerenciar Usuários",
    my_balance: "Meu Saldo",
    balance_description:
      "Gerencie o saldo da sua conta e histórico de pagamentos",
    current_balance: "Saldo Atual",

    // Reservations
    reservations: "Reservas",
    reservations_menu_description: "Gerencie e agende reservas de armários",
    "reservations.title": "Reservas",
    "reservations.allStatuses": "Todos os Status",
    "reservations.active": "Ativo",
    "reservations.cancelled": "Cancelado",
    "reservations.completed": "Concluído",
    "reservations.expired": "Expirado",
    "reservations.createNew": "Criar Nova Reserva",
    "reservations.calendar": "Calendário",
    "reservations.reservationsFor": "Reservas para",
    "reservations.allReservations": "Todas as Reservas",
    "reservations.reservationCode": "Código da Reserva",
    "reservations.startTime": "Hora de Início",
    "reservations.endTime": "Hora de Fim",
    "reservations.accessCode": "Código de Acesso",
    "reservations.notes": "Notas",
    "reservations.edit": "Editar",
    "reservations.cancel": "Cancelar",
    "reservations.noReservations": "Nenhuma reserva encontrada",
    "reservations.locker": "Armário",
    "reservations.selectLocker": "Selecionar um armário",
    "reservations.creating": "Criando...",
    "reservations.create": "Criar",
    "reservations.editReservation": "Editar Reserva",
    "reservations.updating": "Atualizando...",
    "reservations.update": "Atualizar",
    "reservations.confirmCancel":
      "Tem certeza de que deseja cancelar esta reserva?",
  },
  az: {
    // Navigation
    main_menu: "Əsas Menyu",
    borrow: "Götürmək",
    return: "Qaytarmaq",
    admin: "İdarəetmə",
    users: "İstifadəçilər",
    items: "Əşyalar",
    lockers: "Şkaflar",
    logs: "Qeydlər",
    logout: "Çıxış",

    // Login
    login: "Giriş",
    username: "İstifadəçi adı",
    password: "Şifrə",
    login_button: "Daxil ol",
    login_error: "Yanlış istifadəçi adı və ya şifrə",
    login_description: "Ağıllı Şkaf Sisteminə daxil olmaq üçün giriş edin",
    enter_username: "İstifadəçi adınızı daxil edin",
    enter_password: "Şifrənizi daxil edin",
    fill_all_fields: "Zəhmət olmasa bütün sahələri doldurun",
    demo_credentials:
      "Demo məlumatları: admin/admin123, student1/student123, manager/manager123, supervisor/supervisor123",
    dont_have_account: "Hesabınız yoxdur?",
    sign_in: "Daxil ol",
    server_error: "Server xətası. Zəhmət olmasa sonra yenidən cəhd edin.",
    network_error: "Şəbəkə xətası. Zəhmət olmasa bağlantınızı yoxlayın.",
    login_failed: "Giriş uğursuz oldu. Yenidən cəhd edin.",
    invalid_credentials:
      "Yanlış istifadəçi adı və ya şifrə. Yenidən cəhd edin.",
    account_locked: "Hesab bloklanıb. Administratorla əlaqə saxlayın.",
    too_many_attempts: "Çox sayda giriş cəhdi. Sonra yenidən cəhd edin.",

    // Main Menu
    welcome: "Xoş gəlmisiniz",
    select_option: "Zəhmət olmasa seçim edin",
    borrow_item: "Əşya Götürmək",
    return_item: "Əşya Qaytarmaq",
    admin_panel: "İdarəetmə Paneli",
    borrow_description: "Mövcud şkaflardan avadanlıq və ya alətlər götürün",
    return_description: "Götürülmüş əşyaları təyin edilmiş şkaflara qaytarın",
    admin_panel_description:
      "İdarəetmə funksiyalarına və sistem idarəçiliyinə daxil olun",
    items_description: "Avadanlıq və alətlərin inventarını idarə edin",
    lockers_description: "Şkafların konfiqurasiyasını və statusunu izləyin",
    payments_menu_description: "Ödənişləri və faktura məlumatlarını idarə edin",
    get_started: "Başlayın",
    quick_overview: "Sürətli Baxış",

    // Borrow
    follow_steps_borrow: "Əşya götürmək üçün addımları izləyin",
    authentication: "Doğrulama",
    choose_authentication_method: "Doğrulama metodunuzu seçin",
    rfid_card: "RFID Kartı",
    scan_rfid: "RFID Kartını Skan Et",
    scan_rfid_description: "Davam etmək üçün RFID kartınızı skan edin",
    simulate_rfid_scan: "RFID Skanını Simulyasiya Et",
    user_id: "İstifadəçi ID",
    enter_user_id: "İstifadəçi ID-nizi daxil edin",
    enter_user_id_description:
      "RFID kartınız yoxdursa, rəqəmli istifadəçi ID-nizi daxil edin",
    continue: "Davam et",
    select_item: "Əşya Seç",
    choose_item_borrow: "Götürmək istədiyiniz əşyanı seçin",
    select_locker: "Şkaf Seç",
    select_available_locker: "Əşyanız üçün mövcud şkaf seçin",
    confirm_borrow: "Götürməni Təsdiq Et",
    confirm_borrowing_details: "Götürmə təfərrüatlarınızı təsdiq edin",
    borrow_success: "Əşya uğurla götürüldü",
    borrow_error: "Əşya götürülmədi",

    // Return
    follow_steps_return: "Əşya qaytarmaq üçün addımları izləyin",
    scan_rfid_return_description:
      "Əşyanızı qaytarmaq üçün RFID kartınızı skan edin",
    enter_user_id_return_description:
      "Əşyanızı qaytarmaq üçün rəqəmli istifadəçi ID-nizi daxil edin",
    select_item_return: "Qaytarılacaq Əşya Seç",
    choose_item_return: "Qaytarmaq istədiyiniz əşyanı seçin",
    confirm_return: "Qaytarmanı Təsdiq Et",
    confirm_return_details: "Qaytarma təfərrüatlarınızı təsdiq edin",
    return_success: "Əşya uğurla qaytarıldı",
    return_error: "Əşya qaytarılmadı",
    error_fetching_items: "Götürülmüş əşyaları əldə etməkdə xəta",
    borrowed_on: "Götürülmə tarixi",
    back_to_main_menu: "Əsas Menyuya Qayıt",

    // Dashboard
    dashboard_description: "Ağıllı Şkaf Sisteminin ümumi görünüşü",

    // Items Management
    items_management: "Əşyaların İdarəsi",
    items_management_description:
      "Şkaf sistemindəki avadanlıq və alətləri idarə edin",
    search_items: "Əşyaları axtar...",
    search_borrowed_items: "Götürülmüş əşyaları axtar...",
    no_items_found: "Heç bir əşya tapılmadı",
    try_different_search: "Fərqli axtarış termini cəhd edin",
    all_lockers: "Bütün Şkaflar",
    add_item: "Əşya Əlavə Et",
    edit_item: "Əşyanı Redaktə Et",
    delete_item: "Əşyanı Sil",
    confirm_delete_item: "Bu əşyanı silmək istədiyinizə əminsiniz?",
    failed_add_item: "Əşya əlavə edilmədi",
    failed_update_item: "Əşya yenilənmədi",
    failed_delete_item: "Əşya silinmədi",

    // Active Borrows (Emprunts)
    active_borrows: "Aktiv Götürmələr",
    active_borrows_description:
      "Hazırda götürülmüş bütün əşyaları görün və idarə edin",
    active_borrows_menu_description:
      "Bütün aktiv götürmələri və onların statusunu görün",
    search_borrows: "Götürmələri axtar...",
    filter_by_user: "İstifadəçiyə görə filtr",
    filter_by_item: "Əşyaya görə filtr",
    filter_by_date: "Tarixə görə filtr",
    all_users: "Bütün İstifadəçilər",
    all_items: "Bütün Əşyalar",
    showing: "Göstərilir",
    of: "dən",
    duration: "Müddət",
    days: "gün",
    hours: "saat",
    less_than_hour: "1 saatdan az",
    no_active_borrows: "Aktiv Götürmə Yoxdur",
    no_active_borrows_description: "Hazırda sistemdə aktiv götürmə yoxdur",
    failed_export_borrows: "Götürmələr ixrac edilmədi",

    // Admin
    dashboard: "İdarəetmə Paneli",
    total_users: "Ümumi İstifadəçilər",
    total_items: "Ümumi Əşyalar",
    total_lockers: "Ümumi Şkaflar",
    recent_activity: "Son Fəaliyyət",
    view_current_borrows: "Hazırda götürülmüş əşyaları görün",
    view_activity_logs: "Bütün sistem fəaliyyətini görün",
    add_edit_users: "İstifadəçiləri əlavə edin, redaktə edin və ya silin",
    completed: "Tamamlandı",
    unknown: "Naməlum",

    // Common
    loading: "Yüklənir...",
    error: "Xəta",
    success: "Uğur",
    cancel: "Ləğv et",
    save: "Saxla",
    delete: "Sil",
    edit: "Redaktə et",
    add: "Əlavə et",
    search: "Axtar",
    no_data: "Məlumat mövcud deyil",

    // Registration
    create_account: "Hesabınızı yaradın",
    register_description: "Ağıllı Şkaf Sisteminə qoşulun",
    register: "Qeydiyyat",
    email: "E-poçt",
    first_name: "Ad",
    last_name: "Soyad",
    confirm_password: "Şifrəni Təsdiq Et",
    already_have_account: "Artıq hesabınız var?",
    username_placeholder: "İstifadəçi adını daxil edin",
    email_placeholder: "E-poçt ünvanını daxil edin",
    first_name_placeholder: "Adı daxil edin",
    last_name_placeholder: "Soyadı daxil edin",
    password_placeholder: "Şifrəni daxil edin",
    confirm_password_placeholder: "Şifrənizi təsdiq edin",
    password_requirements: "Şifrə tələbləri:",
    min_8_characters: "Ən azı 8 simvol",
    one_uppercase: "Bir böyük hərf",
    one_lowercase: "Bir kiçik hərf",
    one_number: "Bir rəqəm",
    one_special: "Bir xüsusi simvol",
    all_fields_required: "Bütün sahələr tələb olunur",
    passwords_dont_match: "Şifrələr uyğun gəlmir",
    password_requirements_not_met: "Şifrə tələbləri qarşılanmır",
    invalid_email: "Yanlış e-poçt ünvanı",
    registration_successful: "Qeydiyyat uğurlu! Zəhmət olmasa giriş edin.",
    registration_failed: "Qeydiyyat uğursuz. Yenidən cəhd edin.",
    student_id: "Tələbə ID",
    student_id_placeholder: "Tələbə ID-nizi daxil edin",
    scan_card: "Kartı Skan Et",
    scan_card_description: "Və ya tələbə kartınızı skan edin",
    generate_test_id: "Test ID Yarat",

    // User Management
    add_user: "İstifadəçi Əlavə Et",
    edit_user: "İstifadəçini Redaktə Et",
    delete_user: "İstifadəçini Sil",
    search_users: "İstifadəçiləri axtar...",
    filter_by_role: "Rola görə filtr",
    all_roles: "Bütün Rollar",
    new_password: "Yeni Şifrə",
    leave_blank: "cari şifrəni saxlamaq üçün boş buraxın",
    role: "Rol",
    student: "Tələbə",
    user_management: "İstifadəçi İdarəsi",
    manage_accounts: "İstifadəçi hesablarını və icazələri idarə edin",
    no_users_found: "Heç bir istifadəçi tapılmadı",
    get_started_adding: "İlk istifadəçinizi əlavə etməklə başlayın",
    user: "İstifadəçi",
    actions: "Əməliyyatlar",
    confirm_delete: "Bu istifadəçini silmək istədiyinizə əminsiniz?",
    failed_add_user: "İstifadəçi əlavə edilmədi",
    failed_update_user: "İstifadəçi yenilənmədi",
    failed_delete_user: "İstifadəçi silinmədi",
    save_changes: "Dəyişiklikləri Saxla",

    // Reports
    reports: "Hesabatlar",
    report_type: "Hesabat Növü",
    date_range: "Tarix Aralığı",
    start_date: "Başlama Tarixi",
    end_date: "Bitmə Tarixi",
    daily: "Günlük",
    weekly: "Həftəlik",
    monthly: "Aylıq",
    yearly: "İllik",
    transactions: "Əməliyyatlar",
    export_excel: "Excel İxrac Et",
    export_pdf: "PDF İxrac Et",
    generate: "Yarat",
    generating: "Yaradılır...",
    summary: "Xülasə",
    total_transactions: "Ümumi Əməliyyatlar",
    borrows: "Götürmələr",
    returns: "Qaytarmalar",
    unique_users: "Unikal İstifadəçilər",
    unique_items: "Unikal Əşyalar",
    transaction_details: "Əməliyyat Təfərrüatları",
    action: "Əməliyyat",
    timestamp: "Vaxt Damğası",
    locker: "Şkaf",
    overview: "Ümumi Baxış",
    quick_actions: "Sürətli Əməliyyatlar",
    generate_report: "Hesabat Yarat",
    view_transactions: "Əməliyyatları və analitikləri görün",

    // Lockers
    lockers_management: "Şkafların İdarəsi",
    edit_locker: "Şkafı Redaktə Et",
    locker_name: "Şkaf Adı",
    location: "Yer",
    status: "Status",
    available: "Mövcud",
    occupied: "Məşğul",
    maintenance: "Təmir",
    reserved: "Rezerv",
    inactive: "Qeyri-aktiv",
    available_lockers: "Mövcud Şkaflar",
    reserved_lockers: "Rezerv Şkaflar",
    maintenance_lockers: "Təmirdə Olan Şkaflar",
    inactive_lockers: "Qeyri-aktiv Şkaflar",
    no_available_lockers: "Mövcud Şkaf Yoxdur",
    all_lockers_occupied: "Bütün şkaflar hazırda məşğul və ya təmirdədir.",
    locker_with_item: "Seçilmiş Əşya ilə Şkaf",
    empty_lockers: "Boş Şkaflar",
    contains_item: "Əşya Var",
    no_item: "Əşya Yoxdur",
    item_locker_unavailable: "Əşyanın Şkafı Əlçatmazdır",
    item_locker_unavailable_desc:
      "Bu əşyanı ehtiva edən şkaf hazırda əlçatmazdır (təmir, rezerv və ya qeyri-aktiv).",
    no_borrowed_items: "Götürülmüş Əşya Yoxdur",
    no_borrowed_items_desc:
      "Hazırda götürülmüş əşyanız yoxdur. Əşya götürmək üçün Götürmə səhifəsini ziyarət edin.",
    lockers_management_description:
      "Şkafların yerlərini və statusunu idarə edin",
    search_lockers: "Şkafları axtar...",
    all_status: "Bütün Statuslar",
    no_lockers_found: "Heç bir şkaf tapılmadı",
    get_started_adding_locker: "İlk şkafınızı əlavə etməklə başlayın",
    rs485_configuration: "RS485 Konfiqurasiyası",
    rs485_address: "RS485 Ünvanı",
    rs485_address_help: "Kart ünvanı (0-31 dipswitch)",
    rs485_locker_number: "Şkaf Nömrəsi",
    rs485_locker_number_help: "Şkaf nömrəsi (1-24)",
    rs485_protocol_info:
      "Protokol: 5A5A 00 [ÜNVAN] 00 04 00 01 [ŞKAF_NÖMRƏSI] [CHECKSUM]",

    // Logs
    logs_title: "Sistem Qeydləri",
    logs_description:
      "Sistem fəaliyyətini və istifadəçi əməliyyatlarını izləyin",
    search_logs: "Qeydləri axtar...",
    all_actions: "Bütün Əməliyyatlar",
    filters: "Filtrlər",
    export_csv: "CSV İxrac Et",
    clear_filters: "Filtrləri Təmizlə",
    no_logs_found: "Heç bir qeyd tapılmadı",
    try_adjusting_search:
      "Axtarış və ya filtr kriteriyalarınızı düzəltməyə çalışın",
    no_activity_logged: "Hələ heç bir fəaliyyət qeyd edilməyib",
    unknown_user: "Naməlum İstifadəçi",
    unknown_item: "Naməlum Əşya",
    unknown_locker: "Naməlum Şkaf",
    just_now: "İndi",
    minutes_ago: "dəqiqə əvvəl",
    hours_ago: "saat əvvəl",
    failed_export_logs: "Qeydlər ixrac edilmədi",

    // Payments
    payments: "Ödənişlər",
    payments_description: "Ödənişləri və faktura məlumatlarını idarə edin",
    search_payments: "Ödənişləri axtar...",
    new_payment: "Yeni Ödəniş",
    download_excel: "Excel Yüklə",
    add_money: "Pul Əlavə Et",
    balance: "Balans",
    amount: "Məbləğ",
    description: "Təsvir",
    date: "Tarix",
    currency: "Valyuta",
    payment_history: "Ödəniş Tarixçəsi",
    no_payments_found: "Heç bir ödəniş tapılmadı",
    no_payments_yet: "Hələ heç bir ödəniş edilməyib",
    failed_add_payment: "Ödəniş əlavə edilmədi",
    failed_add_money: "Pul əlavə edilmədi",
    all_statuses: "Bütün Statuslar",
    failed: "Uğursuz",
    show: "Göstər",
    per_page: "səhifə başına",
    all: "Hamısı",
    page: "Səhifə",
    add_locker: "Şkaf Əlavə Et",
    item_name: "Əşya Adı",
    description_optional: "Təsvir (İstəyə bağlı)",
    system_logs: "Sistem Qeydləri",
    manage_users: "İstifadəçiləri İdarə Et",
    my_balance: "Mənim Balansım",
    balance_description: "Hesab balansınızı və ödəniş tarixçənizi idarə edin",
    current_balance: "Cari Balans",

    // Reservations
    reservations: "Rezervasiyalar",
    reservations_menu_description:
      "Şkaf rezervasiyalarını idarə edin və planlaşdırın",
    "reservations.title": "Rezervasiyalar",
    "reservations.allStatuses": "Bütün Statuslar",
    "reservations.active": "Aktiv",
    "reservations.cancelled": "Ləğv edilmiş",
    "reservations.completed": "Tamamlanmış",
    "reservations.expired": "Vaxtı keçmiş",
    "reservations.createNew": "Yeni Rezervasiya Yarat",
    "reservations.calendar": "Təqvim",
    "reservations.reservationsFor": "Rezervasiyalar",
    "reservations.allReservations": "Bütün Rezervasiyalar",
    "reservations.reservationCode": "Rezervasiya Kodu",
    "reservations.startTime": "Başlama Vaxtı",
    "reservations.endTime": "Bitmə Vaxtı",
    "reservations.accessCode": "Giriş Kodu",
    "reservations.notes": "Qeydlər",
    "reservations.edit": "Redaktə et",
    "reservations.cancel": "Ləğv et",
    "reservations.noReservations": "Heç bir rezervasiya tapılmadı",
    "reservations.locker": "Şkaf",
    "reservations.selectLocker": "Şkaf seçin",
    "reservations.creating": "Yaradılır...",
    "reservations.create": "Yarat",
    "reservations.editReservation": "Rezervasiyanı Redaktə Et",
    "reservations.updating": "Yenilənir...",
    "reservations.update": "Yenilə",
    "reservations.confirmCancel":
      "Bu rezervasiyanı ləğv etmək istədiyinizə əminsiniz?",
  },
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState("en");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language");
    if (savedLanguage && translations[savedLanguage]) {
      setCurrentLanguage(savedLanguage);
    }
  }, []);

  const changeLanguage = (language) => {
    if (translations[language]) {
      setCurrentLanguage(language);
      localStorage.setItem("language", language);
    }
  };

  const t = (key) => {
    return translations[currentLanguage][key] || translations.en[key] || key;
  };

  const value = {
    currentLanguage,
    changeLanguage,
    t,
    availableLanguages: ["en", "fr", "tr", "az", "es", "pt-BR"],
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
